package com.example.asistentedocumental.models

import java.sql.Time

data  class CheckListGeneral(
    val id: Int = 0,
    val create_at: Time?,
    val update_at: Time?,
    val delete_at: Time?,
    val List_1_equip:String="",
    val List_1_A_1_1:String="",
    val List_1_A_1_2:String="",
    val List_1_A_1_3:String="",
    val List_1_A_1_4:String="",
    val List_1_A_1_5:String="",
    val List_1_A_1_6:String="",
    val List_1_A_1_7:String="",
    val List_1_A_1_8:Boolean=false,
    val List_1_A_2_1:String="",
    val List_1_A_2_2:String="",
    val List_1_A_2_3:String="",
    val List_1_A_2_4:String="",
    val List_1_A_2_5:String="",
    val List_1_A_2_6:String="",
    val List_1_A_2_7:String="",
    val List_1_A_2_8:Boolean=false,
    val List_1_A_3_1:String="",
    val List_1_A_3_2:String="",
    val List_1_A_3_3:String="",
    val List_1_A_3_4:String="",
    val List_1_A_3_5:String="",
    val List_1_A_3_6:String="",
    val List_1_A_3_7:String="",
    val List_1_A_3_8:Boolean=false,
    val List_1_B_1_1_1:String="",
    val List_1_B_1_1_2:String="",
    val List_1_B_1_1_3:String="",
    val List_1_B_1_2_1:String="",
    val List_1_B_1_2_2:String="",
    val List_1_B_1_2_3:String="",
    val List_1_B_1_3_1:String="",
    val List_1_B_1_3_2:String="",
    val List_1_B_1_3_3:String="",
    val List_1_B_1_4_1:String="",
    val List_1_B_1_4_2:String="",
    val List_1_B_1_4_3:String="",
    val List_1_B_1_5_1:String="",
    val List_1_B_1_5_2:String="",
    val List_1_B_1_5_3:String="",
    val List_1_B_1_6_1:String="",
    val List_1_B_1_6_2:String="",
    val List_1_B_1_6_3:String="",
    val List_1_B_1_7_1:String="",
    val List_1_B_1_7_2:String="",
    val List_1_B_1_7_3:String="",
    val List_1_B_1_8_1:String="",
    val List_1_B_1_8_2:String="",
    val List_1_B_1_8_3:String="",
    val List_1_B_1_9_1:String="",
    val List_1_B_1_9_2:String="",
    val List_1_B_1_9_3:String="",
    val List_1_B_2_1:String="",
    val List_1_B_2_2:String="",
    val List_1_B_2_3:String="",
    val List_1_B_2_4:String="",
    val List_1_B_3_1:String="",
    val List_1_B_3_2:String="",
    val List_1_B_3_3:String="",
    val List_1_B_4_1:String="",
    val List_1_B_4_2:String="",
    val List_1_B_5:String="",
    val List_1_B_6:String="",
    val List_1_B_7OK:Boolean= false
    val List_1_B_8:String="",

)